"""Generate re/led_tables.h from dump/flash.bin (stock app). Run from the repository root."""
d = open('dump/flash.bin', 'rb').read()

def arr(name, addr, n, comment='', cols=16):
    b = d[addr:addr + n]
    out = [f'/* {comment} */', f'/* source: flash 0x{addr:05x}..0x{addr + n - 1:05x} ({n} bytes) */',
           f'static const uint8_t {name}[{n}] = {{']
    for i in range(0, n, cols):
        out.append('    ' + ', '.join(f'0x{x:02x}' for x in b[i:i + cols]) + ',')
    out.append('};\n')
    return '\n'.join(out)

def arr2(name, addr, rows, cols, comment=''):
    out = [f'/* {comment} */', f'/* source: flash 0x{addr:05x}..0x{addr + rows * cols - 1:05x} */',
           f'static const uint8_t {name}[{rows}][{cols}] = {{']
    for r in range(rows):
        b = d[addr + r * cols:addr + (r + 1) * cols]
        out.append('    { ' + ', '.join(f'0x{x:02x}' for x in b) + ' },')
    out.append('};\n')
    return '\n'.join(out)

parts = ['''/* led_tables.h -- lookup tables extracted from the stock HyperX Pulsefire Dart
 * firmware (dump/flash.bin, app 0x50000-0x68000, FW 1.1.0.8).
 * Generated by re/tools/gen_led_tables.py. See re/led_effects.md for how each is used.
 */
#ifndef LED_TABLES_H
#define LED_TABLES_H
#include <stdint.h>

#define LED_PWM_TOP            320u   /* COUNTERTOP, PWM clock 1 MHz -> 3.125 kHz (0x5f220 / cfg 0x646cc) */
#define LED_BREATH_LAST_IDX    187u   /* RAM 0x20002526 (RW-init 0xBB, never written) */
#define LED_RTC_HZ             32768u /* app_timer tick (RTC1 PRESCALER 0) */
#define LED_DPI_STEP_TICKS     0x3d7u /* 983 ticks = 30.0 ms: DPI indicator / restore step */
#define LED_POLL_IND_TICKS     0x2666u/* 9830 ticks = 300 ms: polling-rate indicator step */
#define LED_LOWBAT_CRIT_TICKS  0x4000u/* 0.5 s blink half-period (SOC < 5 %) */
#define LED_LOWBAT_LOW_TICKS   0x8000u/* 1.0 s blink half-period (SOC <= threshold) */
/* APP_TIMER_TICKS(ms) as used by the stock code (0x503e8 = 64-bit udiv): */
#define LED_MS_TO_TICKS(ms)    ((uint32_t)((((uint64_t)(ms)) * 32768u + 500u) / 1000u))
''',
    arr('led_gamma', 0x66996, 256,
        'Gamma table, used ONLY by HSV->RGB 0x59d9c (spectrum hue cycle, reactive random colour).'),
    arr('led_breath', 0x66b52, 188,
        'Breath/pulse envelope used by 0x58348 (out = c * tbl[idx] >> 8), idx 0..187: '
        '0 at idx 0, ramp to 255 at idx 63, hold 255 to idx 94, ramp to 0 at idx 157, 0 until 187. '
        'Used by breathing, reactive, DPI indicator, charging.'),
    arr('led_breath_inv_unused', 0x66a96, 188,
        'Complementary envelope (255 -> 0 -> 255). NOT referenced by any literal in the app [HYPOTHESIS: dead data]. '
        'Directly follows the gamma table.'),
    arr2('led_cycle_colours', 0x66c1a, 9, 3,
         'Breathing sub-mode 2 colour cycle (R,G,B), indexed by state[3] 0..8 after each breath (0x62318, 0x628da).'),
    arr2('led_zone_pins', 0x66c14, 2, 3,
         'Pin per zone/channel for 0x64428: [zone][R,G,B]. Pin = port*32+pin. '
         'Zone0 (rear logo): P0.08,P0.04,P0.06. Zone1 (scroll wheel): P0.12,P0.11,P1.09.'),
    arr('led_pins_alt_unused', 0x66c0e, 6,
        'Pins interleaved zone1/zone0 (R1,R0,G1,G0,B1,B0). No literal reference found [HYPOTHESIS: unused].'),
    arr('led_pwm_pins', 0x646c4, 8,
        'nrfx_pwm pin table: PWM0 OUT0..3 = P0.12,P0.11,P1.09,P0.08; PWM1 OUT0..1 = P0.04,P0.06, rest 0xFF (unused). '
        'Channel of a pin = index in this table (0x5f1a0): idx>>2 = instance, idx&3 = channel.'),
    arr('led_pair_pin_a', 0x66948, 2,
        'Pairing-success GPIO table A, indexed by 0x200024d5 (always 1 in practice -> P0.11): {P1.09, P0.11}.'),
    arr('led_pair_pin_b', 0x6694a, 2,
        'Pairing-success GPIO table B, indexed by 0x200024d5 (1 -> P0.04): {P0.06, P0.04}.'),
    '''/* Default 13-byte zone block (RW image 0x200027b1, both zones identical):
 * eff=1 (spectrum), sub=2, speed=0x20, [3..5]=20 00 00 (unused), brightness=50,
 * colour1=FFFFFF, colour2=000000. */
static const uint8_t led_zone_default[13] = {
    0x01, 0x02, 0x20, 0x20, 0x00, 0x00, 0x32, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00,
};

#endif /* LED_TABLES_H */
''']
open('re/led_tables.h', 'w', newline='\n').write('\n'.join(parts))
print('ok')
