#!/usr/bin/env python3
"""Stock-derived data for the firmware: the PMW3389 SROM and the LED tables.

This data is NOT in the repository (PixArt SROM and HyperX tables are not ours to publish).
Take it from your own full flash dump of the mouse (see docs/flashing.md, "Dump"):

    python tools/extract_blobs.py dump/flash.bin [output_dir]

writes fw/mouse/src/stock_blobs.c, which the normal build compiles.

    python tools/extract_blobs.py --placeholder

writes fw/mouse/src/stock_blobs_placeholder.c: the same arrays filled with marker bytes. It is
used for release builds (CONFIG_PULSEDART_BLOB_PLACEHOLDER); tools/make_firmware.py replaces
the markers in the built image with the data from your dump.

Only stock firmware 1.1.0.8 is accepted (the SHA-256 of every blob is checked).
"""
import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "fw" / "mouse" / "src"

# name, flash address in the stock image, length, C dimensions
BLOBS = [
    ("pmw3389_srom", 0x64926, 4094, "[PMW3389_SROM_LEN]"),
    ("led_gamma", 0x66996, 256, "[256]"),
    ("led_breath", 0x66B52, 188, "[188]"),
    ("led_cycle_colours", 0x66C1A, 27, "[9][3]"),
]
# sha256 of the four blobs concatenated, stock firmware 1.1.0.8
BLOBS_SHA = "8fdc0821c962723021f5e8ffb93b794c54520fd4b3d70958c0c5336827587504"


def sha(b):
    return hashlib.sha256(b).hexdigest()


def stock_blobs(dump):
    """{name: bytes} from a full 1 MB flash dump of stock 1.1.0.8."""
    if len(dump) != 1024 * 1024:
        sys.exit("expected a full 1 MB flash dump of the nRF52840")
    data = {name: dump[addr:addr + n] for name, addr, n, _ in BLOBS}
    got = sha(b"".join(data[name] for name, *_ in BLOBS))
    if got != BLOBS_SHA:
        sys.exit(f"the dump does not contain stock firmware 1.1.0.8 (blob sha256 {got})")
    return data


def placeholder(name, n):
    """Marker bytes for a blob: a SHA-256 counter stream, unique and easy to find again."""
    out = b""
    i = 0
    while len(out) < n:
        out += hashlib.sha256(f"pulsedart-placeholder:{name}:{i}".encode()).digest()
        i += 1
    return out[:n]


def c_file(data, comment):
    lines = [f"/* {comment} */", '#include "stock_blobs.h"', ""]
    for name, addr, n, dims in BLOBS:
        b = data[name]
        lines.append(f"/* stock flash 0x{addr:05x}, {n} bytes */")
        lines.append(f"const uint8_t {name}{dims} = {{")
        if dims.count("[") == 2:
            lines += ["\t{ " + ", ".join(f"0x{x:02x}" for x in b[i:i + 3]) + " },"
                      for i in range(0, n, 3)]
        else:
            lines += ["\t" + ", ".join(f"0x{x:02x}" for x in b[i:i + 12]) + ","
                      for i in range(0, n, 12)]
        lines += ["};", ""]
    return "\n".join(lines)


def main():
    args = sys.argv[1:]
    if args == ["--placeholder"]:
        data = {name: placeholder(name, n) for name, _, n, _ in BLOBS}
        path = OUT / "stock_blobs_placeholder.c"
        path.write_text(c_file(data, "Marker bytes, NOT real data: generated by "
                                     "tools/extract_blobs.py --placeholder.\n * A release "
                                     "build links this file; tools/make_firmware.py puts the "
                                     "real data in."), newline="\n")
        print("written:", path)
        return
    if len(args) not in (1, 2):
        sys.exit(__doc__)
    out = Path(args[1]) if len(args) == 2 else OUT
    data = stock_blobs(Path(args[0]).read_bytes())
    out.mkdir(parents=True, exist_ok=True)
    path = out / "stock_blobs.c"
    path.write_text(c_file(data, "Extracted from the stock Pulsefire Dart firmware 1.1.0.8 by "
                                 "tools/extract_blobs.py.\n * Do not publish: PixArt SROM and "
                                 "HyperX tables (see re/sensor.md, re/led_effects.md)."),
                    newline="\n")
    print("written:", path)


if __name__ == "__main__":
    main()
